apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway-acme
spec:
  metrics:
    secret: wavefront-secret
  tracing:
    secret: wavefront-secret
  api:
    serverUrl: http://gateway-acme.spring.animalrescue.online
    title: "ACME Fitness Gateway"
    description: "ACME Fitness application for Spring Cloud Gateway commercial product demos."
    documentation: "https://github.com/vmwarecloudadvocacy/acme_fitness_demo/"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "http://api-portal.spring.animalrescue.online"
      allowedMethods:
      - "GET"
      - "PUT"
      - "POST"
      - "DELETE"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: scg-ingress
spec:
  rules:
    - host: gateway-acme.spring.animalrescue.online
      http:
        paths:
          - backend:
              serviceName: gateway-acme
              servicePort: 80
